import "server-only";

import { createReadStream } from "node:fs";
import { mkdir, stat, unlink, writeFile } from "node:fs/promises";
import path from "node:path";

/**
 * Disk storage for task attachments.
 *
 * Files deliberately do **not** live under `public/`. Anything served from
 * there is world-readable to whoever guesses or shares the URL, and an
 * attachment belongs to a task inside a private workspace — so uploads go to a
 * directory outside the web root and are streamed back only through a route
 * that checks membership first.
 *
 * The on-disk name is always a generated id, never anything the uploader
 * supplied, which is what makes path traversal impossible regardless of what
 * the original filename contained.
 */

const UPLOAD_DIR = process.env.UPLOAD_DIR ?? path.join(process.cwd(), "uploads");

/** 10 MB. Keep `serverActions.bodySizeLimit` in next.config.ts above this. */
export const MAX_ATTACHMENT_BYTES = 10 * 1024 * 1024;

/**
 * Types allowed to render inline in the browser. Everything else downloads.
 * SVG is deliberately absent: it can carry script, and served inline from our
 * own origin that would be stored XSS.
 */
const INLINE_SAFE = new Set([
  "image/png",
  "image/jpeg",
  "image/gif",
  "image/webp",
  "application/pdf",
]);

export function isInlineSafe(mimeType: string | null | undefined) {
  return Boolean(mimeType && INLINE_SAFE.has(mimeType));
}

/**
 * Reduces a user-supplied filename to something safe to store and display.
 * This governs the label only — the bytes are written under a generated id, so
 * nothing here is load-bearing for path safety.
 */
export function cleanFilename(raw: string) {
  const base = raw.split(/[/\\]/).pop() ?? "file";
  // Control characters would corrupt the Content-Disposition header, and a
  // quote or backslash would let a crafted name break out of it.
  const cleaned = base.replace(/[\u0000-\u001f\u007f"\\]/g, "").trim();
  return (cleaned || "file").slice(0, 200);
}

function pathFor(id: string) {
  // `id` is generated by us, but resolve and re-check anyway: this function is
  // the only thing standing between a caller and the filesystem.
  const resolved = path.resolve(UPLOAD_DIR, id);
  if (path.dirname(resolved) !== path.resolve(UPLOAD_DIR)) {
    throw new Error("Refusing to resolve an attachment path outside the upload directory.");
  }
  return resolved;
}

export async function saveAttachment(id: string, bytes: Buffer) {
  await mkdir(UPLOAD_DIR, { recursive: true });
  await writeFile(pathFor(id), bytes);
}

export async function deleteAttachment(id: string) {
  try {
    await unlink(pathFor(id));
  } catch (error) {
    // Already gone is a success for our purposes — the row is what matters.
    if ((error as NodeJS.ErrnoException).code !== "ENOENT") throw error;
  }
}

/** Opens the stored file for streaming, or returns null when it is missing. */
export async function readAttachment(id: string) {
  const file = pathFor(id);
  try {
    const info = await stat(file);
    if (!info.isFile()) return null;
    return { stream: createReadStream(file), size: info.size };
  } catch {
    return null;
  }
}
